# Site settings
title: The Life Aquatic
description: A Minecraft mod about fun with underwater adventure!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lifeaquatic.aergonaut.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
